HopDongCSHT/Controllers/HopDongController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HopDongCSHT.DAO;
using HopDongCSHT.HDContext;

namespace HopDongCSHT.Controllers
{
    public class HopDongController : Controller
    {
        private CSHT_QNHEntities db = new CSHT_QNHEntities();

        // GET: HopDong
        public ActionResult Index()
        {
            return View(db.HopDongs.ToList());
        }

        // GET: HopDong/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HopDong hopDong = db.HopDongs.Find(id);
            HopDongDAO dao = new HopDongDAO();
            ViewBag.LstFile = dao.DetailsHD(id);
            if (hopDong == null)
            {
                return HttpNotFound();
            }
            return View(hopDong);
        }

        // GET: HopDong/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HopDong/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,SoHopDong,Ten_HD,LoaiHD,CSHT_DiaChi,Ten_A,A_DiaChi,A_DienThoai,A_MST,A_DaiDien,A_ChucVu,ThoiGianThue,TuNgay,DenNgay,DonGia")] HopDong hopDong)
        {
            if (ModelState.IsValid)
            {
                db.HopDongs.Add(hopDong);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(hopDong);
        }

        // GET: HopDong/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HopDong hopDong = db.HopDongs.Find(id);
            if (hopDong == null)
            {
                return HttpNotFound();
            }
            return View(hopDong);
        }

        // POST: HopDong/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,SoHopDong,Ten_HD,LoaiHD,CSHT_DiaChi,Ten_A,A_DiaChi,A_DienThoai,A_MST,A_DaiDien,A_ChucVu,ThoiGianThue,TuNgay,DenNgay,DonGia")] HopDong hopDong)
        {
            if (ModelState.IsValid)
            {
                db.Entry(hopDong).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(hopDong);
        }

        // GET: HopDong/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HopDong hopDong = db.HopDongs.Find(id);
            if (hopDong == null)
            {
                return HttpNotFound();
            }
            return View(hopDong);
        }

        // POST: HopDong/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HopDong hopDong = db.HopDongs.Find(id);
            db.HopDongs.Remove(hopDong);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HopDongCSHT/Views/HopDong/Delete.cshtml
@model HopDongCSHT.HDContext.HopDong

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HopDong</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SoHopDong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoHopDong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ten_HD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_HD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LoaiHD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiHD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CSHT_DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CSHT_DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ten_A)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_A)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.A_DiaChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.A_DiaChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.A_DienThoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.A_DienThoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.A_MST)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.A_MST)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.A_DaiDien)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.A_DaiDien)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.A_ChucVu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.A_ChucVu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ThoiGianThue)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ThoiGianThue)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TuNgay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TuNgay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DenNgay)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DenNgay)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonGia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonGia)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HopDongCSHT/Views/HopDong/Details.cshtml
@model HopDongCSHT.HDContext.HopDong

@{
    ViewBag.Header = "Hợp đồng Cơ sở hạ tầng " + Model.SoHopDong;
    ViewBag.Bread = "Hợp đồng CSHT";
    ViewBag.Title = "Hợp đồng CSHT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row margin20">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Thông tin hợp đồng</h3>
        </div>
        <div class="box-body">
            <form class="form-horizontal ">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="txtHopDongID" class="col-sm-4 control-label">Số hợp đồng</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" value="@Model.SoHopDong" id="txtHopDongID" placeholder="Số hợp đồng">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtTenHD" class="col-sm-4 control-label">Tên hợp đồng</label>

                        <div class="col-sm-8">
                            <textarea class="form-control" rows="5" placeholder="" id="txtTenHD">@Model.Ten_HD</textarea>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="txtLoaiHD" class="col-sm-4 control-label">Loại Hợp đồng</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtLoaiHD" value="@Model.LoaiHD" placeholder="Loại Hợp đồng">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtDiaChi" class="col-sm-4 control-label">Địa chỉ CSHT</label>
                        <div class="col-sm-8">
                            <textarea class="form-control" rows="3" placeholder="" id="txtDiaChi">@Model.CSHT_DiaChi</textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtSTT" class="col-sm-4 control-label">Số tháng thuê</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtSTT" value="@Model.ThoiGianThue" placeholder="Số tháng thuê">
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Thuê từ ngày</label>
                        <div class=" col-sm-8">
                            @*<div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>*@
                            <input type="text" id="tuNgay" class="form-control" value="@Model.TuNgay.ToString("dd/MM/yyyy")" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">
                        </div>
                        <!-- /.input group -->
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Thuê đến ngày</label>

                        <div class=" col-sm-8">
                            @*<div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>*@
                            <input type="text" id="denNgay" value="@Model.DenNgay.ToString("dd/MM/yyyy")" class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">
                        </div>
                        <!-- /.input group -->
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Đơn giá/ Tháng</label>
                        <div class="col-sm-8">
                            <input type="text" id="txtDonGia" value="@Model.DonGia" class="form-control">
                        </div>

                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row margin20">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Thông tin Bên A</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
                @*<button type="button" class="btn btn-box-tool" data-widget="remove" data-toggle="tooltip" title="" data-original-title="Remove">
                        <i class="fa fa-times"></i>
                    </button>*@
            </div>
        </div>
        <div class="box-body">
            <form class="form-horizontal">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="txtTenA" class="col-sm-4 control-label">Tên Bên A</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtTenA" value="@Model.Ten_A" placeholder="Tên A">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtA_Diachi" class="col-sm-4 control-label">Địa chỉ Bên A</label>
                        <div class="col-sm-8">
                            <textarea class="form-control" rows="3" placeholder="" id="txtA_Diachi">@Model.A_DiaChi</textarea>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="txtSDT" class="col-sm-4 control-label">Số điện thoại</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtSDT" value="@Model.A_DienThoai" placeholder="Số điện thoại">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtMST" class="col-sm-4 control-label">Mã số thuế</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtMST" value="@Model.A_MST" placeholder="Mã số thuế">
                        </div>
                    </div>

                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label for="txtA_DaiDien" class="col-sm-4 control-label">Đại diện bên A</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtA_DaiDien" value="@Model.A_DaiDien" placeholder="Đại diện bên A">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtA_ChucVu" class="col-sm-4 control-label">Chức vụ</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtA_ChucVu" value="@Model.A_ChucVu" placeholder="Chức vụ">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="row margin20">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Thông tin tập tin đính kèm</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="" data-original-title="Collapse">
                    <i class="fa fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="box-body">
            <div class="col-md-3"></div>
            <div class="col-lg-6">
                <form class="form-horizontal">
                    <table class="table display responsive cell-border" style="width:100%" id="example">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayName("Tên File")
                                </th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in ViewBag.LstFile as IEnumerable<HopDongCSHT.HDContext.Luu_File>)
                            {
                                <tr>

                                    <td>
                                        @Html.Label(item.Ten_File)
                                    </td>
                                    <td>

                                        <a href="@Url.Action("Download", "HopDong",new { id = item.ID, name = item.Duong_dan })">
                                            <i class="fa fa-download"></i> <span>Download</span>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </form>

            </div>

        </div>
        <div class="box-footer text-center">
            <a href="/HopDong/" class="btn btn-info" style="width: 150px">Đóng</a>
        </div>
    </div>
</div>



@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('[data-mask]').inputmask();
            $('#txtDonGia').simpleMoneyFormat();



        });


    </script>
}

HopDongCSHT/Views/HopDong/Index.cshtml
@model IEnumerable<HopDongCSHT.HDContext.HopDong>

@{
    ViewBag.Header = "Hợp đồng Cơ sở hạ tầng";
    ViewBag.Bread = "Hợp đồng CSHT";
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row margin20">
    <div class="box box-info">
        <div class="box-header">
            <h3 class="box-title">Tìm kiếm</h3>
        </div>
        <div class="box-body">
            <form class="form-horizontal ">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="txtHopDongID" class="col-sm-4 control-label">Số hợp đồng</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtHopDongID" placeholder="Số hợp đồng">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="txtTenHD" class="col-sm-4 control-label">Tên hợp đồng</label>

                        <div class="col-sm-8">
                            <input type="text" class="form-control" id="txtTenHD" placeholder="Tên hợp đồng">
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Từ ngày</label>

                        <div class="input-group col-sm-8">
                            @*<div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>*@
                            <input type="text" id="tuNgay" class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">
                        </div>
                        <!-- /.input group -->
                    </div>
                    <div class="form-group">
                        <label class="col-sm-4 control-label">Đến ngày</label>

                        <div class="input-group col-sm-8">
                            @*<div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>*@
                            <input type="text" id="denNgay" class="form-control" data-inputmask="'alias': 'dd/mm/yyyy'" data-mask="">
                        </div>
                        <!-- /.input group -->
                    </div>
                </div>
            </form>
        </div>
        <div class="box-footer">
            <button id="btnSearch" class="btn btn-info center-block">Tìm kiếm</button>
        </div>
    </div>
</div>
<div class="row text-right">
    <p>
        <a href="/HopDong/Create" class="btn btn-flat bg-primary margin">Thêm mới</a>
        <button type="button" class="btn btn-default btn-flat">Sửa</button>
        <button type="button" class="btn btn-flat btn-default  margin">Xóa</button>
    </p>
</div>
<div class="row">
    <div class="box box-info">
        <div class="box-body">
            <table class="table display responsive cell-border" style="width:100%" id="example">
                <thead>
                    <tr>
                        <th></th>
                        <th>
                            @Html.DisplayName("Số hợp đồng")
                        </th>
                        <th>
                            @Html.DisplayName("Tên hợp đồng")
                        </th>
                        <th>
                            @Html.DisplayName("Địa chỉ CSHT")
                        </th>
                        <th>
                            @Html.DisplayName("Từ ngày")
                        </th>
                        <th>
                            @Html.DisplayName("Đến Ngày")
                        </th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.Label(item.ID.ToString())</td>
                            <td>
                                @Html.Label(item.SoHopDong)
                            </td>
                            <td>
                                @Html.Label(item.Ten_HD)
                            </td>
                            <td>
                                @Html.Label(item.CSHT_DiaChi)
                            </td>
                            <td>
                                @Html.Label(item.TuNgay.ToShortDateString())
                            </td>
                            <td>
                                @Html.Label(item.DenNgay.ToShortDateString())
                            </td>
                            <td>
                                @*@Html.ActionLink(" ", "Details", new { id = item.ID }, new { @class = "fa fa-eye" })*@
                                @*<a href="/HopDong/Details='" class="dropdown-toggle">
                                        <i class="fa fa-eye"></i>
                                    </a>*@
                                <a href=@Url.Action("Details","HopDong" , new { id = item.ID }) class="dropdown-toggle" data-toggle="tooltip" title="Xem chi tiết">
                                    <i class="fa fa-eye"></i>
                                </a>
                                <a href="#" class="dropdown-toggle" data-toggle="tooltip" title="Sửa">
                                    <i class="fa fa-edit"></i>
                                </a>
                                <a href="#" class="dropdown-toggle" data-toggle="tooltip" title="Xóa">
                                    <i class="fa fa-trash-o"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>



@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#example').DataTable({
                responsive: true,
                select: true,
                "columnDefs": [
                    {
                        "targets": [0],
                        "visible": false,
                        "searchable": false
                    },
                    {
                        "targets": [4],
                        "type":'date'
                    },
                ]


            });

            $('[data-mask]').inputmask();

            //Ham search theo tu ngay - den ngay
            $.fn.dataTable.ext.search.push(
                function (settings, data, dataIndex) {


                    var valid = true;
                    var min = moment($("#tuNgay").val());
                    if (!min.isValid()) { min = null; }

                    var max = moment($("#denNgay").val());
                    if (!max.isValid()) { max = null; }

                    if (min === null && max === null) {
                        // no filter applied or no date columns
                        valid = true;
                    }
                    else {

                        $.each(settings.aoColumns, function (i, col) {

                            if (col.type == "date") {
                                var cDate = moment(data[i], 'DD/MM/YYYY');

                                if (cDate.isValid()) {
                                    if (max !== null && max.isBefore(cDate)) {
                                        valid = false;
                                    }
                                    if (min !== null && cDate.isBefore(min)) {
                                        valid = false;
                                    }
                                }
                                else {
                                    valid = false;
                                }
                            }
                        });
                    }
                    return valid;
                });

            $('#btnSearch').click(function () {
                table.column(1).search($("#txtHopDongID").val()).column(2).search($("#txtTenHD").val()).draw();
            });
        });


    </script>
}